import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Layout } from "@/components/shared/layout/Layout";

const geistHelvet = localFont({
  src: "./fonts/HelveticaNeueLight.otf",
  variable: "--font-helvet",
  weight: "100 400 500 600 900",
});
const geistThings = localFont({
  src: "./fonts/Things To Remember.otf",
  variable: "--font-things-to-remember",
  weight: "100 400 500 600 900",
});

const geistBalltimore = localFont({
  src: "./fonts/BalltimoreSans-Demo.otf",
  variable: "--font-balltimore",
  weight: "100 400 500 600 900",
});

const geistSuisse = localFont({
  src: "./fonts/fonnts.com-Suisse_Intl_Regular.ttf",
  variable: "--font-suisse",
  weight: "100 400 500 600 900",
});

const geistAeon = localFont({
  src: "./fonts/AeonikTRIAL-Regular.otf",
  variable: "--font-aeon",
  weight: "100 400 500 600 900",
});

const geistAeonBold = localFont({
  src: "./fonts/AeonikTRIAL-Bold.otf",
  variable: "--font-aeon-bold",
  weight: "100 400 500 600 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistHelvet.variable} ${geistAeonBold.variable} ${geistAeon.variable} ${geistSuisse.variable} ${geistBalltimore.variable} ${geistThings.variable} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
